### ISSUE TITLE
 京东日资产变动脚本通知问题

### ISSUE THREAD

**Issue by wk333** [X1a0He/jd_scripts_fixed#10]
JD_BEAN_CHANGE_SENDNUM 在青龙面板上设置大于已有账号数会发送多条通知
比如有9个账号，如果变量为9，只会发送一条通知
但是变量变成10，会一个账号一个账号的单条进行发送通知

**Comment by X1a0He** [comment]
知道了，感谢反馈

> JD_BEAN_CHANGE_SENDNUM 在青龙面板上设置大于已有账号数会发送多条通知
> 比如有9个账号，如果变量为9，只会发送一条通知
> 但是变量变成10，会一个账号一个账号的单条进行发送通知

**Comment by X1a0He** [comment]
已修复 [jd_bean_change_xh.js](https://github.com/X1a0He/jd_scripts_fixed/blob/main/jd_bean_change_xh.js)
Fix time: 2021-09-14 22:54

> JD_BEAN_CHANGE_SENDNUM 在青龙面板上设置大于已有账号数会发送多条通知
> 比如有9个账号，如果变量为9，只会发送一条通知
> 但是变量变成10，会一个账号一个账号的单条进行发送通知
