### ISSUE TITLE
关键词过滤问题

### ISSUE THREAD

**Issue by cqmoyf** [X1a0He/jd_scripts_fixed#14]
在关键词过滤的黑名单中有填写 “面膜”这个关键词，但是使用中有些被过滤，有些又成功申请，日志如下：

第 1 次获取试用商品成功，tabId:1 的 第 1/17 页
获取到商品 13 条
检测 tabId:1 的 第 1/17 页 第 2 个商品
伊芳澜 菁采美肌补水面膜30ml补水保湿深层锁水改善暗沉提亮肤色男女通用5片\/盒 1盒（5片）
商品被过滤，已申请试用人数大于预设人数 

商品状态异常，未找到skuTitle

商品已申请试用：伊芳澜 臻耀美肌面膜25ml补水保湿改善暗沉护肤品男女通用深层锁水 一盒（5片）

检测 tabId:1 的 第 1/17 页 第 3 个商品
理肤泉 黑膜清痘修复面膜27g*5片（去角质 收缩毛孔 控油清洁）
商品被过滤，含有关键词 面膜

商品已申请试用：雪花秀玉璨净颜撕拉面膜免水洗清洁面膜150ml（细腻毛孔 保湿滋润 深层清洁 提亮肤色）

检测 tabId:1 的 第 1/17 页 第 4 个商品
兰芝益生睡眠面膜70ml(免洗罐装面膜 补水保湿 不油腻 化妆品 护肤 男女)中秋节礼物
商品被过滤，含有关键词 补水

商品未到申请时间：麻辣王子麻辣条 休闲食品30小包网红健康零食小吃湖南特产面筋零食礼盒儿时怀旧办公室大礼包 很麻很辣1盒-550g（30小包）

检测 tabId:1 的 第 1/17 页 第 5 个商品
江中食疗江中猴姑无糖酥性饼干 无蔗糖饼干960g（40包）20天装 盒装 早餐猴头菇饼干点心休闲零食
商品被过滤，已申请试用人数大于预设人数 

检测 tabId:1 的 第 1/17 页 第 6 个商品
泓一 冰皮蛋糕草莓味 蛋糕营养早餐代餐休闲零食网红点心糕点麻薯雪媚娘800g
商品被过滤，19.90 < 50 

商品已申请试用：雀巢脆脆鲨休闲零食鲨可棒蛋卷椰子味注心饼干吃60g下午茶办公室零食

商品已申请试用：雀巢脆脆鲨休闲零食鲨可棒蛋卷芝士味注心饼干吃60g下午茶办公室零食

检测 tabId:1 的 第 1/17 页 第 7 个商品
江中食疗江中猴姑海盐芝士苏打饼干864g/36小包 有手提便携礼盒装 代餐早餐猴头菇饼干点心休闲零食
商品被过滤，已申请试用人数大于预设人数 

检测 tabId:1 的 第 1/17 页 第 8 个商品
江中食疗江中猴姑益生菌发酵酸奶饼干960g/40小包 盒装 无蔗糖代餐早餐猴头菇饼干蛋糕点心休闲零食
商品被过滤，已申请试用人数大于预设人数 

当前试用组长度为：0

间隔等待中，请等待 2 秒

**Comment by X1a0He** [comment]
已申请使用的意思是你已经申请过这个东西了，这次流程就不会将这件商品添加到待试用组

> 在关键词过滤的黑名单中有填写 “面膜”这个关键词，但是使用中有些被过滤，有些又成功申请，日志如下：
> 
> 第 1 次获取试用商品成功，tabId:1 的 第 1/17 页
> 获取到商品 13 条
> 检测 tabId:1 的 第 1/17 页 第 2 个商品
> 伊芳澜 菁采美肌补水面膜30ml补水保湿深层锁水改善暗沉提亮肤色男女通用5片/盒 1盒（5片）
> 商品被过滤，已申请试用人数大于预设人数
> 
> 商品状态异常，未找到skuTitle
> 
> 商品已申请试用：伊芳澜 臻耀美肌面膜25ml补水保湿改善暗沉护肤品男女通用深层锁水 一盒（5片）
> 
> 检测 tabId:1 的 第 1/17 页 第 3 个商品
> 理肤泉 黑膜清痘修复面膜27g*5片（去角质 收缩毛孔 控油清洁）
> 商品被过滤，含有关键词 面膜
> 
> 商品已申请试用：雪花秀玉璨净颜撕拉面膜免水洗清洁面膜150ml（细腻毛孔 保湿滋润 深层清洁 提亮肤色）
> 
> 检测 tabId:1 的 第 1/17 页 第 4 个商品
> 兰芝益生睡眠面膜70ml(免洗罐装面膜 补水保湿 不油腻 化妆品 护肤 男女)中秋节礼物
> 商品被过滤，含有关键词 补水
> 
> 商品未到申请时间：麻辣王子麻辣条 休闲食品30小包网红健康零食小吃湖南特产面筋零食礼盒儿时怀旧办公室大礼包 很麻很辣1盒-550g（30小包）
> 
> 检测 tabId:1 的 第 1/17 页 第 5 个商品
> 江中食疗江中猴姑无糖酥性饼干 无蔗糖饼干960g（40包）20天装 盒装 早餐猴头菇饼干点心休闲零食
> 商品被过滤，已申请试用人数大于预设人数
> 
> 检测 tabId:1 的 第 1/17 页 第 6 个商品
> 泓一 冰皮蛋糕草莓味 蛋糕营养早餐代餐休闲零食网红点心糕点麻薯雪媚娘800g
> 商品被过滤，19.90 < 50
> 
> 商品已申请试用：雀巢脆脆鲨休闲零食鲨可棒蛋卷椰子味注心饼干吃60g下午茶办公室零食
> 
> 商品已申请试用：雀巢脆脆鲨休闲零食鲨可棒蛋卷芝士味注心饼干吃60g下午茶办公室零食
> 
> 检测 tabId:1 的 第 1/17 页 第 7 个商品
> 江中食疗江中猴姑海盐芝士苏打饼干864g/36小包 有手提便携礼盒装 代餐早餐猴头菇饼干点心休闲零食
> 商品被过滤，已申请试用人数大于预设人数
> 
> 检测 tabId:1 的 第 1/17 页 第 8 个商品
> 江中食疗江中猴姑益生菌发酵酸奶饼干960g/40小包 盒装 无蔗糖代餐早餐猴头菇饼干蛋糕点心休闲零食
> 商品被过滤，已申请试用人数大于预设人数
> 
> 当前试用组长度为：0
> 
> 间隔等待中，请等待 2 秒

**Comment by cqmoyf** [comment]
谢谢，明白了。
