### ISSUE TITLE
jd_try的一些提议

### ISSUE THREAD

**Issue by Mr-Coffee666** [X1a0He/jd_scripts_fixed#2]
1.获取试用商品之前判断当日时候仍剩余试用机会（每个账号每天最多只能申请300个，如果已申请300个就不再获取试用商品了，因为很耗时）
2.日志打印-去除当前试用组的打印。每页获取完都会打印一次当前试用组，打印的都是一些普通人看不懂的trialActivityId组成的数组，没什么必要。如确有必要可以仅仅只打印当前数组长度
2.日志打印-商品黑名单过滤希望加上关键字

**Comment by X1a0He** [comment]
> 1.获取试用商品之前判断当日时候仍剩余试用机会（每个账号每天最多只能申请300个，如果已申请300个就不再获取试用商品了，因为很耗时）
> 2.日志打印-去除当前试用组的打印。每页获取完都会打印一次当前试用组，打印的都是一些普通人看不懂的trialActivityId组成的数组，没什么必要。如确有必要可以仅仅只打印当前数组长度
> 2.日志打印-商品黑名单过滤希望加上关键字

感谢建议
第二点已经可以通过环境变量来控制是否输出日志，请查看JD_TRY_PLOG
黑名单过滤加上关键字这一点你的意思应该是想表达过滤的时候显示对应商品被过滤的关键字对吧
这个会加上的，第一点还没看能不能实时获取到，保守估计不能

**Comment by gitiray** [comment]
似乎没有接口可以直接查看已申请数量。
一种办法是遍历已申请的列表，按申请时间去统计但是反而把问题弄复杂了。

最好的办法是自己控制好每天申请的总数（运行次数*每次申请数量）。

**Comment by X1a0He** [comment]
> 似乎没有接口可以直接查看已申请数量。
> 一种办法是遍历已申请的列表，按申请时间去统计但是反而把问题弄复杂了。
> 
> 最好的办法是自己控制好每天申请的总数（运行次数*每次申请数量）。

无法实现，因为每次运行的变量都是新的，无法将已申请的次数记录下来，但也可能有办法，由于技术有限，如果你有更好的建议，可以告诉我

**Comment by X1a0He** [comment]
[jd_try_xh.js](https://github.com/X1a0He/jd_scripts_fixed/blob/main/jd_try_xh.js)
Fix time: 2021-09-08 17:22

**Comment by Mr-Coffee666** [comment]
关于第一条，可以尝试先获取一个商品进行申请，就可以判断是否当天已申请数量已满
