### ISSUE TITLE
jd_unsubscribe_xh.js死循环，显示还有一个关注店铺未清空

### ISSUE THREAD

**Issue by lafVinson** [X1a0He/jd_scripts_fixed#23]
jd_unsubscribe_xh.js死循环，显示还有一个关注店铺未清空
进入jd app查看，关注店铺显示1，但是点进去看明细却又没有关注店铺，
脚本一直在获取到1个关注店铺，然后清空，清空失败，又获取到一个关注店铺死循环，请问有解决办法吗，谢谢！

**Comment by X1a0He** [comment]
带一下日志上来，不然哪知道怎么解决

> jd_unsubscribe_xh.js死循环，显示还有一个关注店铺未清空 进入jd app查看，关注店铺显示1，但是点进去看明细却又没有关注店铺， 脚本一直在获取到1个关注店铺，然后清空，清空失败，又获取到一个关注店铺死循环，请问有解决办法吗，谢谢！

**Comment by lafVinson** [comment]
你好，就是这样，然后就无限循环下去了，持续到几个小时后脚本运行周期超时。谢谢

=====京东账号6 实际我的内心内部变量=====
$.unsubscribeGoodsNum: 0
$.unsubscribeShopsNum: 0
$.goodsTotalNum: 0
$.shopsTotalNum: 0
$.commIdList: 
$.shopIdList: 
================
正在获取已关注的商品...
当前已关注商品：5个
正在取消收藏商品...
成功取消收藏商品：5个

正在获取已关注的店铺...
当前已关注店铺：3个
正在执行批量取消关注店铺...
已成功取消关注店铺：3个

正在获取已关注的商品...
当前已关注商品：1个
正在取消收藏商品...
成功取消收藏商品：6个

正在获取已关注的商品...
当前已关注商品：0个
不执行取消收藏商品

正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败

正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败

正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败

正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败

正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败

正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败

正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败

正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败

正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败

正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败

正在获取已关注的店铺...
