### ISSUE TITLE
tabID从0开始？

### ISSUE THREAD

**Issue by ericli911** [X1a0He/jd_scripts_fixed#24]
我自定义了变量export JD_TRY_TABID="@9@10@11@12@7@1@2@3@4@5@6@8@14@15@16" ，
运行后从日志里发现tabId: object, 0,9,10,11,12,7,1,2,3,4,5,6,8,14,15,16
也就是说最前面多了个0，
而且这个tabId:0 的 页数非常多，从日志看“tabId:0 的 第 1/514 页”，完全没有机会跑后面的tabID了，
请问这个0有什么方法可以去掉？谢
![submit](https://user-images.githubusercontent.com/31944102/141674083-e4a209aa-f17b-4a9b-bf13-442b162cfa9b.png)
谢

**Comment by X1a0He** [comment]
这个原因是因为你在9的前面多加了一个@，所以脚本会默认多读一个0在9的前面，如果你多加几个@，就会多加几个0，解决方法就是吧9前面的@去掉

> 我自定义了变量export JD_TRY_TABID="@9@10@11@12@7@1@2@3@4@5@6@8@14@15@16" ， 运行后从日志里发现tabId: object, 0,9,10,11,12,7,1,2,3,4,5,6,8,14,15,16 也就是说最前面多了个0， 而且这个tabId:0 的 页数非常多，从日志看“tabId:0 的 第 1/514 页”，完全没有机会跑后面的tabID了， 请问这个0有什么方法可以去掉？谢 ![submit](https://user-images.githubusercontent.com/31944102/141674083-e4a209aa-f17b-4a9b-bf13-442b162cfa9b.png) 谢

**Comment by ericli911** [comment]
感谢感谢
