### ISSUE TITLE
资产通知错误

### ISSUE THREAD

**Issue by EchoChan314** [X1a0He/jd_scripts_fixed#25]
正在进行第 1 次发送通知，发送数量：20
telegram发送通知消息失败！！

HTTPError: Response code 400 (Bad Request)
    at Request.<anonymous> (/ql/node_modules/.pnpm/got@11.8.2/node_modules/got/dist/source/as-promise/index.js:117:42)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: undefined,
  timings: {
    start: 1636959388120,
    socket: 1636959388120,
    lookup: 1636959388155,
    connect: 1636959388322,
    secureConnect: 1636959388496,
    upload: 1636959388496,
    response: 1636959389033,
    end: 1636959389033,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 35,
      tcp: 167,
      tls: 174,
      request: 0,
      firstByte: 537,
      download: 0,
      total: 913
    }
  }
}
正在进行最后一次发送通知，发送数量：0
Telegram发送通知消息成功🎉。

🔔京东日资产变动, 结束! 🕛 74.006 秒

另外大佬方便的话把jdcookie.js这几个依赖加上吧，方便小白。

**Comment by X1a0He** [comment]
通知文件不归我管

> 正在进行第 1 次发送通知，发送数量：20 telegram发送通知消息失败！！
> 
> HTTPError: Response code 400 (Bad Request) at Request. (/ql/node_modules/.pnpm/got@11.8.2/node_modules/got/dist/source/as-promise/index.js:117:42) at runMicrotasks () at processTicksAndRejections (internal/process/task_queues.js:95:5) { code: undefined, timings: { start: 1636959388120, socket: 1636959388120, lookup: 1636959388155, connect: 1636959388322, secureConnect: 1636959388496, upload: 1636959388496, response: 1636959389033, end: 1636959389033, error: undefined, abort: undefined, phases: { wait: 0, dns: 35, tcp: 167, tls: 174, request: 0, firstByte: 537, download: 0, total: 913 } } } 正在进行最后一次发送通知，发送数量：0 Telegram发送通知消息成功🎉。
> 
> 🔔京东日资产变动, 结束! 🕛 74.006 秒
> 
> 另外大佬方便的话把jdcookie.js这几个依赖加上吧，方便小白。
