### ISSUE TITLE
批量取消商品和店铺关注的脚本失效了

### ISSUE THREAD

**Issue by Hyper-Beast** [X1a0He/jd_scripts_fixed#29]
![image](https://user-images.githubusercontent.com/18001712/146696745-5d893d01-26e3-4852-a446-4bd3ca4f158a.png)

应该不是我个人的问题，群里其他人也这样，不知道大佬有没有空修复

**Comment by Hyper-Beast** [comment]
![image](https://user-images.githubusercontent.com/18001712/146698099-a8ad99a7-ef54-4b4d-9925-ab7e47ba77c5.png)

我换了这个可以了
https://raw.githubusercontent.com/Aaron-lv/sync/jd_scripts/jd_unsubscribe.js

**Comment by X1a0He** [comment]
已修复
- 2021-12-26 15:00 Fix [jd_unsubscribe_xh.js](https://github.com/X1a0He/jd_scripts_fixed/blob/main/jd_unsubscribe_xh.js)
```
修复了获取数据失败的问题
```
