### ISSUE TITLE
JD_Try

### ISSUE THREAD

**Issue by hajiuhajiu** [X1a0He/jd_scripts_fixed#3]
非常感谢作者更新， 
目前获得申请成功数量还是不对， 有待领取商品时通知还是0

**Comment by X1a0He** [comment]
> 非常感谢作者更新，
> 目前获得申请成功数量还是不对， 有待领取商品时通知还是0

感谢反馈，如果可以的话，希望通过tg交流，目前我没有申请成功的ck，如果你不介意提供，可以通过tg发给我，联系方式在readme

**Comment by X1a0He** [comment]
[jd_try_xh.js](https://github.com/X1a0He/jd_scripts_fixed/blob/main/jd_try_xh.js)
Fix time: 2021-09-08 17:22
