### ISSUE TITLE
京东试用现在出了 付费试用，能过滤掉吗

### ISSUE THREAD

**Issue by oudaiyi** [X1a0He/jd_scripts_fixed#30]
![image](https://user-images.githubusercontent.com/96033220/147532466-7b72acd4-6f1b-48b2-92b2-8a910f22a674.png)

**Comment by X1a0He** [comment]
- 2022-01-25 15:42 Fix [jd_try_xh.js](https://github.com/X1a0He/jd_scripts_fixed/blob/main/jd_try_xh.js)
```
新增环境变量 JD_TRY_TOTALPAGES 用于指定每页遍历的最大页数
新增环境变量 JD_TRY_UNIFIED 用于指定是否采用统一试用组，详情请看脚本 args_xh 下的注释
修复了获取tabList失败的问题
修复了无法获取试用申请成功的问题
```


> ![image](https://user-images.githubusercontent.com/96033220/147532466-7b72acd4-6f1b-48b2-92b2-8a910f22a674.png)
