### ISSUE TITLE
你好反馈下京东试用和清空购物车目前的问题

### ISSUE THREAD

**Issue by lxrcbw** [X1a0He/jd_scripts_fixed#31]
前段时间开始的吧 获取不到试用中选的结果 会提示403 清空购物车脚本直接目前是运行不了 之前都是正常的

**Comment by X1a0He** [comment]
京东试用已修复，清空购物车没收到反馈
- 2022-01-25 15:42 Fix [jd_try_xh.js](https://github.com/X1a0He/jd_scripts_fixed/blob/main/jd_try_xh.js)
```
新增环境变量 JD_TRY_TOTALPAGES 用于指定每页遍历的最大页数
新增环境变量 JD_TRY_UNIFIED 用于指定是否采用统一试用组，详情请看脚本 args_xh 下的注释
修复了获取tabList失败的问题
修复了无法获取试用申请成功的问题
```


> 前段时间开始的吧 获取不到试用中选的结果 会提示403 清空购物车脚本直接目前是运行不了 之前都是正常的
