### ISSUE TITLE
试用不显示中了多少  了···

### ISSUE THREAD

**Issue by cui521** [X1a0He/jd_scripts_fixed#34]
![image](https://user-images.githubusercontent.com/46080261/148944155-dffbd962-694b-4a82-b5d6-a404760406be.png)

**Comment by X1a0He** [comment]
- 2022-01-25 15:42 Fix [jd_try_xh.js](https://github.com/X1a0He/jd_scripts_fixed/blob/main/jd_try_xh.js)
```
新增环境变量 JD_TRY_TOTALPAGES 用于指定每页遍历的最大页数
新增环境变量 JD_TRY_UNIFIED 用于指定是否采用统一试用组，详情请看脚本 args_xh 下的注释
修复了获取tabList失败的问题
修复了无法获取试用申请成功的问题
```

> ![image](https://user-images.githubusercontent.com/46080261/148944155-dffbd962-694b-4a82-b5d6-a404760406be.png)
