### ISSUE TITLE
关于黑白名单的问题

### ISSUE THREAD

**Issue by Naivev** [X1a0He/jd_scripts_fixed#35]
如果把黑名单打开设置关键词，白名单关闭，但是白名单列表设置关键词，
那么此时的状态是获取所有商品，但屏蔽掉黑名单关键词的商品，若黑白名单关键词冲突，以名单优先吗？
还是说因为白名单已经关闭了，即使设置了白名单关键词，但是此时这个设置是无效的？

**Comment by X1a0He** [comment]
这个问题已经在脚本写的很清楚了，关于给白名单的详细脚本注释请认真看
