### ISSUE TITLE
试用成功的商品推送里面还是显示0可以修复下吗？

### ISSUE THREAD

**Issue by gushiduian** [X1a0He/jd_scripts_fixed#5]

**Comment by X1a0He** [comment]
我没有对应试用成功的ck，如果你有，且愿意提供测试，可通过readme的tg链接发给我进行测试

**Comment by X1a0He** [comment]
- 2021-09-09 13:52 Fix [jd_try_xh.js](https://github.com/X1a0He/jd_scripts_fixed/blob/main/jd_try_xh.js)
```
修复试用成功的商品推送里面还是显示0的问题
如果上述问题没有被修复，还是显示0，请带上你的cookie私聊tg找我
```
