### ISSUE TITLE
tabid设置无效，

### ISSUE THREAD

**Issue by JmsWang** [X1a0He/jd_scripts_fixed#7]
首先感谢作者更新，遇到个问题，就是我看默认设置的tabId是12345，但是还是会申请个人护理 - 13，家庭清洁 - 14，食品饮料 - 15这些种类的商品，我通过环境变量的方式也试了一下，也不行

**Comment by X1a0He** [comment]
带上你的设置和日志再提issues

> 首先感谢作者更新，遇到个问题，就是我看默认设置的tabId是12345，但是还是会申请个人护理 - 13，家庭清洁 - 14，食品饮料 - 15这些种类的商品，我通过环境变量的方式也试了一下，也不行

**Comment by JmsWang** [comment]
![image](https://user-images.githubusercontent.com/40831886/132815338-6b51eebe-6777-4ae8-b38e-119b5234a47c.png)
## 开始执行... 2021-09-10 14:29:04


🔔京东试用, 开始!
X1a0He留：遇到问题请把脚本内的注释看一遍再来问，谢谢
开始获取配置文件


====================共5个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2021/9/10 下午2:29:04=====================

共5个京东账号

=====环境变量配置如下=====
jdPrice: number, 10
tabId: object, 1,2,3,4,5,6
titleFilters: object, 教程,英语,辅导,培训,吊坠,面膜,流量卡,情趣,自慰,鞋垫
trialPrice: number, 0
minSupplyNum: number, 1
applyNumFilter: number, 100000
applyInterval: number, 5000
maxLength: number, 100
passZhongCao: boolean, true
printLog: boolean, true
whiteList: boolean, false
whiteListKeywords: object, 
=======================

开始【京东账号1】

第 1 次获取试用商品成功，tabId:1 的 第 1/17 页
获取到商品 13 条
-----------------------------------
第 2 次获取试用商品成功，tabId:1 的 第 2/17 页
获取到商品 12 条
------------------------------------------------
当前试用组长度为：0
间隔等待中，请等待 2 秒
第 3 次获取试用商品成功，tabId:1 的 第 3/17 页
获取到商品 12 条
----------------------------------------------------
商品已申请试用：薇薇酱（VVKEE）省水化妆棉卸妆棉片湿敷拍水 一次性擦脸巾洁面巾70*58mm 80片/盒装
商品未到申请时间：伊芳澜 菁采美肌补水面膜30ml补水保湿深层锁水改善暗沉提亮肤色男女通用5片\/盒 1盒（5片）
商品已申请试用：三元 小方白纯牛奶 250ml*16盒/箱礼盒装儿童学生成人早餐奶营养饮品 （新老包装交替发货）
商品已申请试用：君乐宝白小纯儿童学生营养早餐奶 赵今麦同款 3.3g蛋白新鲜袋 纯牛奶 180ml*12袋
商品已申请试用：君乐宝简醇无蔗糖低温酸奶 0蔗糖浓缩低温酸牛奶 150g*12袋 邓伦同款
商品已申请试用：泓一 冰皮蛋糕草莓味 蛋糕营养早餐代餐休闲零食网红点心糕点麻薯雪媚娘800g

**Comment by JmsWang** [comment]
中间有很多其他商品我删掉了，只保留了这部分不在tabid范围内的商品，后面还有很多日志，太多了就没帖了

**Comment by JmsWang** [comment]
图片好像没有加载成功？图片里就是我设置的环境变量，变量名： JD_TRY_TABID  值： 1@2@3@4@5@6

**Comment by JmsWang** [comment]
然后在我的试用申请页面能看到申请了很多食品饮料和清洁化妆之类的

**Comment by X1a0He** [comment]
tabId为1的时候是精选，精选应该不分什么类别的，只有3开始才是分类

> 然后在我的试用申请页面能看到申请了很多食品饮料和清洁化妆之类的

**Comment by JmsWang** [comment]
获取tabList中...
精选 - 1
闪电试 - 2
家用电器 - 3
手机数码 - 4
电脑办公 - 5
家居家装 - 6
美妆护肤 - 7
服饰鞋包 - 8
母婴玩具 - 9
生鲜美食 - 10
图书音像 - 11
钟表奢品 - 12
个人护理 - 13
家庭清洁 - 14
食品饮料 - 15
更多惊喜 - 16


如果我只申请家用电器，手机数码，电脑办公，家居家装 这几个品类的话，就只填写3456，不填1，是吧

**Comment by X1a0He** [comment]
对的

> 获取tabList中...
> 精选 - 1
> 闪电试 - 2
> 家用电器 - 3
> 手机数码 - 4
> 电脑办公 - 5
> 家居家装 - 6
> 美妆护肤 - 7
> 服饰鞋包 - 8
> 母婴玩具 - 9
> 生鲜美食 - 10
> 图书音像 - 11
> 钟表奢品 - 12
> 个人护理 - 13
> 家庭清洁 - 14
> 食品饮料 - 15
> 更多惊喜 - 16
> 
> 如果我只申请家用电器，手机数码，电脑办公，家居家装 这几个品类的话，就只填写3456，不填1，是吧

**Comment by JmsWang** [comment]
好的，谢谢，我关了
