### ISSUE TITLE
试用中白名单与黑名单的逻辑先后问题。

### ISSUE THREAD

**Issue by Wake2020** [X1a0He/jd_scripts_fixed#8]
在试用脚本的，白名单与黑名单机制中，如果一个商品同时出现了白名单关键词和黑名单关键词，商品不会进入试用组。个人建议，白名单里的商品应当优先，当一个商品同时出现黑名单关键词和白名单关键词时，应当以白名单作为添加进试用组优先逻辑。

举例：比如说 白名单设置了 空调 ，黑名单设置了 系统 关键词，在试用中就会以黑名单过滤这个商品。
实际运行日志：
检测 tabId:1 的 第 15/17 页 第 158 个商品
TCL 新风空调 1.5匹 新一级能效 变频冷暖 灵悉 智能 以旧换新 卧室空调挂机KFRd-35GW/DBp-XJ11+B1新风系统
商品被过滤，含有关键词 系统

**Comment by gitiray** [comment]
那肯定是黑名单先

如果换一个例子【NBMOUNTS电视挂架壁挂墙小米飞利浦海信TCL长虹索尼通用电视机支架17-42英寸固定式/承重30KG】
黑名单关键词【支架】，白名单关键词【电视机】，那最后根本没有过滤效果……

试用真正放出物品本身的机会太少了，**更多的是附属小零件**，所以更应该注重稳定，以**不申请到无意义的内容为前提**

**Comment by X1a0He** [comment]
白名单的优先级永远高于黑名单


> 在试用脚本的，白名单与黑名单机制中，如果一个商品同时出现了白名单关键词和黑名单关键词，商品不会进入试用组。个人建议，白名单里的商品应当优先，当一个商品同时出现黑名单关键词和白名单关键词时，应当以白名单作为添加进试用组优先逻辑。
> 
> 举例：比如说 白名单设置了 空调 ，黑名单设置了 系统 关键词，在试用中就会以黑名单过滤这个商品。
> 实际运行日志：
> 检测 tabId:1 的 第 15/17 页 第 158 个商品
> TCL 新风空调 1.5匹 新一级能效 变频冷暖 灵悉 智能 以旧换新 卧室空调挂机KFRd-35GW/DBp-XJ11+B1新风系统
> 商品被过滤，含有关键词 系统



> 那肯定是黑名单先
> 
> 如果换一个例子【NBMOUNTS电视挂架壁挂墙小米飞利浦海信TCL长虹索尼通用电视机支架17-42英寸固定式/承重30KG】
> 黑名单关键词【支架】，白名单关键词【电视机】，白名单优先的话，根本没有过滤效果……
> 
> 试用真正放出物品本身的机会太少了，**更多的是附属小零件**，所以更应该注重稳定，以**不申请到无意义的内容为前提**

**Comment by Wake2020** [comment]
好的，明白了，大佬辛苦了。
