### ISSUE TITLE
京东试用的执行效率问题

### ISSUE THREAD

**Issue by Scripon** [X1a0He/jd_scripts_fixed#9]
感谢作者的脚本，为我们省了不少事。
但。。。
修改配置：价格》39，申请300个（实际最终150个左右）
3个小时仅能申请8个账号，效率有点慢，能否优化搞下多线程？

**Comment by X1a0He** [comment]
执行效率无法提升，5秒延迟为最低延迟，而且一天24小时你cron表达式写成每X小时运行一次一天不就跑满所有账号了，如果并发的话，京东会风控，风控了又来提issues说为什么被风控，不是我不想他快

> 感谢作者的脚本，为我们省了不少事。
> 但。。。
> 修改配置：价格》39，申请300个（实际最终150个左右）
> 3个小时仅能申请8个账号，效率有点慢，能否优化搞下多线程？

**Comment by Scripon** [comment]
> > 3个小时仅能申请8个账号，效率有点慢，能否优化搞下多线程？



> 执行效率无法提升，5秒延迟为最低延迟，而且一天24小时你cron表达式写成每X小时运行一次一天不就跑满所有账号了，如果并发的话，京东会风控，风控了又来提issues说为什么被风控，不是我不想他快
> 
> > 感谢作者的脚本，为我们省了不少事。
> > 但。。。
> > 修改配置：价格》39，申请300个（实际最终150个左右）
> > 3个小时仅能申请8个账号，效率有点慢，能否优化搞下多线程？

**Comment by Scripon** [comment]
我觉得有个地方可以优化一下，例如第1个ck 在第1次cron时已经跑完，在第2次cron时，脚本还会再跑第1个ck，重新获取待申请的试用商品，这个过程比较耗时，是否可以直接跳过？

**Comment by zhongzeqing** [comment]
被风控了，多久能恢复呀？

**Comment by Ca11back** [comment]
> 我觉得有个地方可以优化一下，例如第1个ck 在第1次cron时已经跑完，在第2次cron时，脚本还会再跑第1个ck，重新获取待申请的试用商品，这个过程比较耗时，是否可以直接跳过？

一天跑一次超时时间拉长就行了吧?

**Comment by Scripon** [comment]
> > 我觉得有个地方可以优化一下，例如第1个ck 在第1次cron时已经跑完，在第2次cron时，脚本还会再跑第1个ck，重新获取待申请的试用商品，这个过程比较耗时，是否可以直接跳过？
> 
> 一天跑一次超时时间拉长就行了吧?

这得看有多少ck吧，虽然我不是呆瓜，但是我都把朋友搞了也有四五十个号，3小时8个号，一天压根跑不完。

**Comment by Scripon** [comment]
其实我有个想法，对于一个docker，一个配置，对容器下的所有账号应该都试用。而在实际申请试用动作之前会匹配各种规则获得复核条件的商品列表，这个列表其实对所有账号也都试用。
所有我想，可以把这个商品列表放到内存里或临时存储本地文件，定期更新内存或本地文件即可，没必要每个账号都去轮询tagid，获得匹配的商品列表，太耗时。
作者，你觉得呢？

**Comment by mingrenbufanganpi** [comment]
有个小建议，获取申请列表不用每个账号都获取一遍，第一次获取完之后，后续每个CK都去申请列表中的东西。

**Comment by GTXGOGOGO** [comment]
qx运行提示

🔔京东试用, 开始!
[Exception]: Can't find variable: process
请问是什么原因

**Comment by X1a0He** [comment]
不支持圈X

> qx运行提示
> 
> 🔔京东试用, 开始!
> [Exception]: Can't find variable: process
> 请问是什么原因

**Comment by GTXGOGOGO** [comment]
好的谢谢

**Comment by seahuang1636** [comment]
node本地能运行么

**Comment by X1a0He** [comment]
- 2022-01-25 15:42 Fix [jd_try_xh.js](https://github.com/X1a0He/jd_scripts_fixed/blob/main/jd_try_xh.js)
```
新增环境变量 JD_TRY_TOTALPAGES 用于指定每页遍历的最大页数
新增环境变量 JD_TRY_UNIFIED 用于指定是否采用统一试用组，详情请看脚本 args_xh 下的注释
修复了获取tabList失败的问题
修复了无法获取试用申请成功的问题
```
